In [3]:
# Chapter 7: Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [7]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [11]:
float_data # NaN is a sentinel value: when present, it indicates a missing (or null) value.

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [13]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [23]:
string_data = pd.Series(["aardark", np.nan, None, "avocado"]) # NA refers to Missing data, which stands for not available.

In [33]:
string_data # The built-in Python None value is also treated as NA

0    aardark
1        NaN
2       None
3    avocado
dtype: object

In [21]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [27]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [29]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [31]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [35]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [37]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [39]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [41]:
# This is the same thing as doing:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [43]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [45]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [47]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [49]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [51]:
# These functions return new objects by default and do not modify the contents of the original object.

In [53]:
data[4] = np.nan

In [55]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [57]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [65]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [67]:
df

          0         1         2
0  0.633379 -0.188013 -0.101596
1 -0.621413  0.934805 -1.436407
2  2.245828 -0.394157  0.313533
3 -1.015369  1.679599  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [69]:
df.iloc[:4, 1] = np.nan

In [71]:
df

          0         1         2
0  0.633379       NaN -0.101596
1 -0.621413       NaN -1.436407
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [73]:
df.iloc[:2, 2] = np.nan

In [75]:
df

          0         1         2
0  0.633379       NaN       NaN
1 -0.621413       NaN       NaN
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [77]:
df.dropna()

          0         1         2
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [81]:
df.dropna(thresh=2) # Keep only rows containing at most a certain number of missing observations.

          0         1         2
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [83]:
df.fillna(0)

          0         1         2
0  0.633379  0.000000  0.000000
1 -0.621413  0.000000  0.000000
2  2.245828  0.000000  0.313533
3 -1.015369  0.000000  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [85]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.633379  0.500000  0.000000
1 -0.621413  0.500000  0.000000
2  2.245828  0.500000  0.313533
3 -1.015369  0.500000  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [87]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [89]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.061619 -0.085516
3  0.278933 -0.066694 -0.136896
4  1.265632  0.747721  0.333549
5 -0.911526  0.256441  0.034631

In [93]:
df.iloc[2:, 1] = np.nan

In [95]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765       NaN -0.085516
3  0.278933       NaN -0.136896
4  1.265632       NaN  0.333549
5 -0.911526       NaN  0.034631

In [97]:
df.iloc[4:, 2] = np.nan

In [99]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765       NaN -0.085516
3  0.278933       NaN -0.136896
4  1.265632       NaN       NaN
5 -0.911526       NaN       NaN

In [103]:
df.fillna(method="ffill") # forward fill

D:\TEMP\ipykernel_13520\2535960854.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill") # forward fill

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.138102 -0.085516
3  0.278933  0.138102 -0.136896
4  1.265632  0.138102 -0.136896
5 -0.911526  0.138102 -0.136896

In [105]:
df.fillna(method="ffill", limit=2)

D:\TEMP\ipykernel_13520\1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.138102 -0.085516
3  0.278933  0.138102 -0.136896
4  1.265632       NaN -0.136896
5 -0.911526       NaN -0.136896

In [107]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [109]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [111]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [5]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [7]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [9]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [11]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [13]:
data["v1"] = range(7)

In [15]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [17]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [23]:
# "duplicated" and "drop_duplicates" by default keep the first observed value combi|nation. 
# Passing keep="last" will return the last one
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [25]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [27]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [29]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [31]:
data["animal"] = data["food"].map(meat_to_animal)

In [33]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [35]:
def get_animal(x):
    return meat_to_animal[x]

In [37]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [2]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [3]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [4]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [5]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [6]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [7]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [17]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["OhiO", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [18]:
data

          one  two  three  four
OhiO        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [19]:
def transform(x):
    return x[:4].upper()

In [20]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [21]:
data.index = data.index.map(transform)

In [22]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [23]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [24]:
data # create a transformed version of a dataset without modifying the original.

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [25]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [26]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [27]:
bins = [18, 25, 35, 60, 100]

In [28]:
age_categories = pd.cut(ages, bins)

In [29]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [31]:
# Outputs an array that represents the category each data point belongs to. 
# Each number corresponds to the position of the interval in the category list.
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [32]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [33]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [34]:
pd.value_counts(age_categories)

C:\Users\Locke\AppData\Local\Temp\ipykernel_12616\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [36]:
pd.Series(age_categories).value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [37]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [38]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [39]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [40]:
data = np.random.uniform(size = 20)

In [41]:
data

array([0.14183762, 0.02509081, 0.25507064, 0.90535758, 0.98466371,
       0.26935295, 0.56856877, 0.91573819, 0.10462058, 0.93272929,
       0.58342359, 0.48397811, 0.15581581, 0.71203824, 0.62331612,
       0.24932962, 0.42964752, 0.48854163, 0.21731694, 0.40892649])

In [42]:
pd.cut(data, 4, precision=2)

[(0.024, 0.26], (0.024, 0.26], (0.024, 0.26], (0.74, 0.98], (0.74, 0.98], ..., (0.024, 0.26], (0.26, 0.5], (0.26, 0.5], (0.024, 0.26], (0.26, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.024, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [43]:
data = np.random.standard_normal(1000)

In [44]:
quartiles = pd.qcut(data, 4, precision=2)

In [45]:
quartiles # obtain roughly equally sized bins.

[(0.68, 3.39], (-0.031, 0.68], (0.68, 3.39], (-0.71, -0.031], (-0.71, -0.031], ..., (-0.031, 0.68], (-0.031, 0.68], (-0.71, -0.031], (-0.031, 0.68], (-2.78, -0.71]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.78, -0.71] < (-0.71, -0.031] < (-0.031, 0.68] < (0.68, 3.39]]

In [46]:
pd.Series(quartiles).value_counts()

(-2.78, -0.71]     250
(-0.71, -0.031]    250
(-0.031, 0.68]     250
(0.68, 3.39]       250
Name: count, dtype: int64

In [47]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.7729999999999997, -1.314]    100
(-1.314, -0.0306]                400
(-0.0306, 1.37]                  400
(1.37, 3.388]                    100
Name: count, dtype: int64

In [3]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))

In [4]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.039895    -0.001904     0.020121     0.071512
std       1.037253     0.959715     1.021091     0.963054
min      -3.307885    -3.188160    -4.106648    -2.671398
25%      -0.619790    -0.678995    -0.671932    -0.597959
50%       0.057015    -0.047932    -0.013736     0.062578
75%       0.752186     0.664939     0.686131     0.677515
max       3.208430     3.226905     3.256160     3.991072

In [5]:
col = data[2]

In [6]:
col[col.abs() > 3]

216    3.256160
400   -4.106648
481    3.079395
634    3.034615
739   -3.152273
753   -3.059182
Name: 2, dtype: float64

In [8]:
# use the any method on a Boolean DataFrame to 
# select all rows having a value exceeding 3 or –3.
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
110  1.585706 -3.188160  0.233903  0.346104
132  3.141658 -0.097743 -1.524578 -0.708210
209 -3.130391  1.137169  1.598413  0.590192
213  3.120847  1.842470 -0.763319 -0.181725
216  0.948868 -1.277980  3.256160  2.101211
288 -3.183775  0.439288 -0.000760  0.333492
311  0.317315  0.474916  0.910558  3.991072
400 -0.485232 -0.114088 -4.106648 -1.114838
481 -1.571596  0.470205  3.079395  0.810130
621 -3.093881  0.608228 -1.187669 -1.308063
634 -1.149771 -0.841001  3.034615  0.904384
739  0.174434 -1.180628 -3.152273  1.257155
753 -2.658944 -0.716147 -3.059182  1.168877
759  0.406406  3.226905  0.011426 -0.360705
794 -3.307885 -1.253889  0.047877 -1.925208
819  3.208430  1.047657 -0.725456 -0.553024

In [9]:
# np.sign(): 
# It returns -1 for negative values, 1 for positive values, and 0 for any zeros.
data[data.abs() > 3] = np.sign(data) * 3

In [10]:
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.040140    -0.001942     0.021069     0.070521
std       1.033689     0.958370     1.015442     0.959519
min      -3.000000    -3.000000    -3.000000    -2.671398
25%      -0.619790    -0.678995    -0.671932    -0.597959
50%       0.057015    -0.047932    -0.013736     0.062578
75%       0.752186     0.664939     0.686131     0.677515
max       3.000000     3.000000     3.000000     3.000000

In [11]:
np.sign(data).head()

     0    1    2    3
0 -1.0 -1.0  1.0 -1.0
1  1.0  1.0  1.0 -1.0
2  1.0  1.0  1.0 -1.0
3 -1.0  1.0  1.0 -1.0
4 -1.0 -1.0  1.0  1.0

In [12]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))

In [13]:
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [16]:
sampler = np.random.permutation(5)

In [17]:
sampler

array([3, 2, 4, 1, 0])

In [18]:
df.take(sampler)

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [19]:
df.iloc[sampler]

    0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6

In [21]:
column_sampler = np.random.permutation(7)

In [22]:
column_sampler

array([0, 5, 3, 1, 4, 6, 2])

In [23]:
df.take(column_sampler, axis="columns")

    0   5   3   1   4   6   2
0   0   5   3   1   4   6   2
1   7  12  10   8  11  13   9
2  14  19  17  15  18  20  16
3  21  26  24  22  25  27  23
4  28  33  31  29  32  34  30

In [25]:
df.sample(n=3) # select a random subset without replacement

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13

In [26]:
choices = pd.Series([5, 7, -1, 6, 4])

In [27]:
choices.sample(n=10, replace=True)

3    6
3    6
1    7
3    6
1    7
1    7
1    7
1    7
4    4
3    6
dtype: int64

In [28]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                   "data1": range(6)})

In [29]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [30]:
pd.get_dummies(df["key"], dtype=float)

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [31]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)

In [32]:
df_with_dummy = df[["data1"]].join(dummies)

In [33]:
df_with_dummy

   data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [34]:
mnames = ["movie_id", "title", "genres"]

In [37]:
movies = pd.read_table("datasets/movielens/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")

In [38]:
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [39]:
dummies = movies["genres"].str.get_dummies("|")

In [41]:
dummies.iloc[:10, :6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [43]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))

In [46]:
movies_windic[:10]

,movie_id,title,genres,Genre_Action,Genre_Adventure,Genre_Animation,Genre_Children's,Genre_Comedy,Genre_Crime,Genre_Documentary,...,Genre_Fantasy,Genre_Film-Noir,Genre_Horror,Genre_Musical,Genre_Mystery,Genre_Romance,Genre_Sci-Fi,Genre_Thriller,Genre_War,Genre_Western
0,1,Toy Story (1995),Animation|Children's|Comedy,0,0,1,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,Jumanji (1995),Adventure|Children's|Fantasy,0,1,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,3,Grumpier Old Men (1995),Comedy|Romance,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3,4,Waiting to Exhale (1995),Comedy|Drama,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,Father of the Bride Part II (1995),Comedy,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
5,6,Heat (1995),Action|Crime|Thriller,1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
6,7,Sabrina (1995),Comedy|Romance,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
7,8,Tom and Huck (1995),Adventure|Children's,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,Sudden Death (1995),Action,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,GoldenEye (1995),Action|Adventure|Thriller,1,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [44]:
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western                                  0
Name: 0, dtype: object

In [47]:
np.random.seed(12345) # to make the example repeatable

In [49]:
values = np.random.uniform(size=10)

In [51]:
values.round(4)

array([0.9296, 0.3164, 0.1839, 0.2046, 0.5677, 0.5955, 0.9645, 0.6532,
       0.7489, 0.6536])

In [52]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [53]:
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [3]:
s = pd.Series([1, 2, 3, None])

In [5]:
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [7]:
s.dtype

dtype('float64')

In [9]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())

In [11]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [13]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [15]:
s.dtype

Int64Dtype()

In [17]:
s[3]

In [19]:
s[3] is pd.NA

True

In [21]:
# The capitalization is necessary.
s = pd.Series([1, 2, 3, None], dtype="Int64")

In [23]:
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [27]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [29]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [31]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})

In [33]:
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [41]:
df["A"] = df["A"].astype("Int64")

In [43]:
df["B"] = df["B"].astype("string")

In [45]:
df["C"] = df["C"].astype("boolean")

In [47]:
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

In [51]:
df["A"].dtype

Int64Dtype()

In [53]:
val = "a,b,  guido"

In [55]:
val.split(",")

['a', 'b', '  guido']

In [57]:
pieces = [x.strip() for x in val.split(",")]

In [59]:
pieces

['a', 'b', 'guido']

In [61]:
first, second, third = pieces

In [63]:
first + "::" + second + "::" + third

'a::b::guido'

In [65]:
"::".join(pieces)

'a::b::guido'

In [67]:
"guido" in val

True

In [71]:
val.index(",")

1

In [75]:
val.find(":")

-1

In [85]:
# The difference between find and index is that index raises an exception 
# if the string isn’t found (versus returning –1).

In [77]:
val

'a,b,  guido'

In [91]:
val.count(",")

2

In [93]:
val.replace(",", "::")

'a::b::  guido'

In [95]:
val.replace(",", "")

'ab  guido'

In [3]:
import re

In [5]:
text = "foo    bar\t baz  \tqux"

In [103]:
# The regex describing one or more whitespace characters is \s+.
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']

In [9]:
regex = re.compile(r"\s+")

In [11]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [13]:
regex.findall(text)

['    ', '\t ', '  \t']

In [15]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""
pattern = r"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}"

# re.IGNORECASE makes the regex case insensitive
regex = re.compile(pattern, flags=re.IGNORECASE)

In [17]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [19]:
m = regex.search(text)

In [21]:
m

In [23]:
text[m.start():m.end()]

'dave@google.com'

In [25]:
print(regex.match(text))

None

In [29]:
print(regex.sub("REDACTED", text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED

In [33]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [35]:
regex = re.compile(pattern, flags=re.IGNORECASE)

In [37]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [39]:
m = regex.match("wesm@bright.net")

In [41]:
m.groups()

('wesm', 'bright', 'net')

In [43]:
print(regex.sub(r"Username: \1, Domain: \2, Suffix: \3", text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com

In [45]:
data = {"Dave": "dave@google.com", "Steve": "steve@gmail.com",
        "Rob": "rob@gmail.com", "Wes": np.nan}

In [47]:
data = pd.Series(data)

In [49]:
data

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [51]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [53]:
data.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [55]:
data_as_string_ext = data.astype('string')

In [57]:
data_as_string_ext

Dave     dave@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [59]:
data_as_string_ext.str.contains("gmail")

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [61]:
pattern = r"([A-Z0-9._%+-]+)@([A-Z0-9.-]+)\.([A-Z]{2,4})"

In [63]:
data.str.findall(pattern, flags=re.IGNORECASE)

Dave     [(dave, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [65]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]

In [67]:
matches

Dave     (dave, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [69]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [71]:
data.str[:5]

Dave     dave@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [73]:
data.str.extract(pattern, flags=re.IGNORECASE)

           0       1    2
Dave    dave  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [75]:
values = pd.Series(['apple', 'orange', 'apple',
                    'apple'] * 2)

In [77]:
values

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
dtype: object

In [79]:
pd.unique(values)

array(['apple', 'orange'], dtype=object)

In [81]:
pd.value_counts(values)

C:\Users\Locke\AppData\Local\Temp\ipykernel_17356\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)

apple     6
orange    2
Name: count, dtype: int64

In [83]:
pd.Series(values).value_counts()

apple     6
orange    2
Name: count, dtype: int64

In [85]:
values = pd.Series([0, 1, 0, 0] * 2)

In [89]:
dim = pd.Series(['apple', 'orange'])

In [91]:
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [93]:
dim

0     apple
1    orange
dtype: object

In [95]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [97]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2

In [99]:
N = len(fruits)

In [101]:
rng = np.random.default_rng(seed=12345)

In [103]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                  columns=['basket_id', 'fruit', 'count', 'weight'])

In [105]:
df

   basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [107]:
fruit_cat = df['fruit'].astype('category')

In [109]:
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [111]:
c = fruit_cat.array

In [113]:
type(c)

pandas.core.arrays.categorical.Categorical

In [115]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [117]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [119]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [121]:
df['fruit'] = df['fruit'].astype('category')

In [123]:
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [125]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])

In [127]:
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [129]:
categories = ['foo', 'bar', 'baz']

In [131]:
codes = [0, 1, 2, 0, 0, 1]

In [133]:
my_cats_2 = pd.Categorical.from_codes(codes, categories)

In [136]:
my_cats_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [138]:
ordered_cat = pd.Categorical.from_codes(codes, categories,
                                        ordered=True)

In [140]:
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [142]:
my_cats_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [144]:
rng = np.random.default_rng(seed=12345)

In [146]:
draws = rng.standard_normal(1000)

In [148]:
draws[:5]

array([-1.42382504,  1.26372846, -0.87066174, -0.25917323, -0.07534331])

In [150]:
bins = pd.qcut(draws, 4)

In [152]:
bins

[(-3.121, -0.675], (0.687, 3.211], (-3.121, -0.675], (-0.675, 0.0134], (-0.675, 0.0134], ..., (0.0134, 0.687], (0.0134, 0.687], (-0.675, 0.0134], (0.0134, 0.687], (-0.675, 0.0134]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.121, -0.675] < (-0.675, 0.0134] < (0.0134, 0.687] < (0.687, 3.211]]

In [154]:
bins = pd.qcut(draws, 4, labels=['Q1', 'Q2', 'Q3', 'Q4'])

In [156]:
bins

['Q1', 'Q4', 'Q1', 'Q2', 'Q2', ..., 'Q3', 'Q3', 'Q2', 'Q3', 'Q2']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [158]:
bins.codes[:10]

array([0, 3, 0, 1, 1, 0, 0, 2, 2, 0], dtype=int8)

In [160]:
bins = pd.Series(bins, name='quartile')

In [162]:
results = (pd.Series(draws)
           .groupby(bins)
           .agg(['count', 'min', 'max'])
           .reset_index())

C:\Users\Locke\AppData\Local\Temp\ipykernel_17356\1248366115.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(bins)

In [164]:
results

  quartile  count       min       max
0       Q1    250 -3.119609 -0.678494
1       Q2    250 -0.673305  0.008009
2       Q3    250  0.018753  0.686183
3       Q4    250  0.688282  3.211418

In [166]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [168]:
N = 10_000_000

In [170]:
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))

In [172]:
categories = labels.astype('category')

In [174]:
labels.memory_usage(deep=True)

520000132

In [176]:
categories.memory_usage(deep=True)

10000512

In [178]:
%time _ = labels.astype('category')

CPU times: total: 234 ms
Wall time: 565 ms

In [180]:
%timeit labels.value_counts()

475 ms ± 56.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [182]:
%timeit categories.value_counts()

55.6 ms ± 3.35 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [184]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)

In [186]:
s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: object

In [188]:
cat_s = s.astype('category')

In [190]:
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [192]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [194]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [196]:
actual_categories = ['a', 'b', 'c', 'd', 'e']

In [198]:
cat_s2 = cat_s.cat.set_categories(actual_categories)

In [200]:
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [202]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [204]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [206]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]

In [208]:
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [210]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [212]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2, dtype='category')

In [214]:
pd.get_dummies(cat_s, dtype=float)

     a    b    c    d
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0  0.0  0.0  1.0
4  1.0  0.0  0.0  0.0
5  0.0  1.0  0.0  0.0
6  0.0  0.0  1.0  0.0
7  0.0  0.0  0.0  1.0