In [3]:
# Chapter 7: Data Cleaning and Preparation

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [7]:
float_data = pd.Series([1.2, -3.5, np.nan, 0])

In [11]:
float_data # NaN is a sentinel value: when present, it indicates a missing (or null) value.

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [13]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [23]:
string_data = pd.Series(["aardark", np.nan, None, "avocado"]) # NA refers to Missing data, which stands for not available.

In [33]:
string_data # The built-in Python None value is also treated as NA

0    aardark
1        NaN
2       None
3    avocado
dtype: object

In [21]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [27]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [29]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [31]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [35]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [37]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [39]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [41]:
# This is the same thing as doing:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [43]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [45]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [47]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [49]:
data.dropna(how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [51]:
# These functions return new objects by default and do not modify the contents of the original object.

In [53]:
data[4] = np.nan

In [55]:
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [57]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [65]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [67]:
df

          0         1         2
0  0.633379 -0.188013 -0.101596
1 -0.621413  0.934805 -1.436407
2  2.245828 -0.394157  0.313533
3 -1.015369  1.679599  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [69]:
df.iloc[:4, 1] = np.nan

In [71]:
df

          0         1         2
0  0.633379       NaN -0.101596
1 -0.621413       NaN -1.436407
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [73]:
df.iloc[:2, 2] = np.nan

In [75]:
df

          0         1         2
0  0.633379       NaN       NaN
1 -0.621413       NaN       NaN
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [77]:
df.dropna()

          0         1         2
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [81]:
df.dropna(thresh=2) # Keep only rows containing at most a certain number of missing observations.

          0         1         2
2  2.245828       NaN  0.313533
3 -1.015369       NaN  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [83]:
df.fillna(0)

          0         1         2
0  0.633379  0.000000  0.000000
1 -0.621413  0.000000  0.000000
2  2.245828  0.000000  0.313533
3 -1.015369  0.000000  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [85]:
df.fillna({1: 0.5, 2: 0})

          0         1         2
0  0.633379  0.500000  0.000000
1 -0.621413  0.500000  0.000000
2  2.245828  0.500000  0.313533
3 -1.015369  0.500000  0.870040
4 -0.499889 -0.516297  0.242709
5 -1.078585  0.226359  0.654416
6  0.309446 -0.705697 -1.287513

In [87]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))

In [89]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.061619 -0.085516
3  0.278933 -0.066694 -0.136896
4  1.265632  0.747721  0.333549
5 -0.911526  0.256441  0.034631

In [93]:
df.iloc[2:, 1] = np.nan

In [95]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765       NaN -0.085516
3  0.278933       NaN -0.136896
4  1.265632       NaN  0.333549
5 -0.911526       NaN  0.034631

In [97]:
df.iloc[4:, 2] = np.nan

In [99]:
df

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765       NaN -0.085516
3  0.278933       NaN -0.136896
4  1.265632       NaN       NaN
5 -0.911526       NaN       NaN

In [103]:
df.fillna(method="ffill") # forward fill

D:\TEMP\ipykernel_13520\2535960854.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill") # forward fill

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.138102 -0.085516
3  0.278933  0.138102 -0.136896
4  1.265632  0.138102 -0.136896
5 -0.911526  0.138102 -0.136896

In [105]:
df.fillna(method="ffill", limit=2)

D:\TEMP\ipykernel_13520\1627181726.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)

          0         1         2
0 -0.708622 -0.358532  0.012731
1 -0.163665  0.138102  0.690906
2 -0.565765  0.138102 -0.085516
3  0.278933  0.138102 -0.136896
4  1.265632       NaN -0.136896
5 -0.911526       NaN -0.136896

In [107]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])

In [109]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [111]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [5]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})

In [7]:
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [9]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [11]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [13]:
data["v1"] = range(7)

In [15]:
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [17]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

In [23]:
# "duplicated" and "drop_duplicates" by default keep the first observed value combi|nation. 
# Passing keep="last" will return the last one
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [25]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                              "pastrami", "corned beef", "bacon",
                              "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [27]:
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [29]:
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}

In [31]:
data["animal"] = data["food"].map(meat_to_animal)

In [33]:
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [35]:
def get_animal(x):
    return meat_to_animal[x]

In [37]:
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [2]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [3]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [4]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [5]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [6]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [7]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [17]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["OhiO", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])

In [18]:
data

          one  two  three  four
OhiO        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [19]:
def transform(x):
    return x[:4].upper()

In [20]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [21]:
data.index = data.index.map(transform)

In [22]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [23]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [24]:
data # create a transformed version of a dataset without modifying the original.

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [25]:
data.rename(index={"OHIO": "INDIANA"},
            columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [26]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [27]:
bins = [18, 25, 35, 60, 100]

In [28]:
age_categories = pd.cut(ages, bins)

In [29]:
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [31]:
# Outputs an array that represents the category each data point belongs to. 
# Each number corresponds to the position of the interval in the category list.
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [32]:
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [33]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [34]:
pd.value_counts(age_categories)

C:\Users\Locke\AppData\Local\Temp\ipykernel_12616\3010498523.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [36]:
pd.Series(age_categories).value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [37]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [38]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]

In [39]:
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [40]:
data = np.random.uniform(size = 20)

In [41]:
data

array([0.14183762, 0.02509081, 0.25507064, 0.90535758, 0.98466371,
       0.26935295, 0.56856877, 0.91573819, 0.10462058, 0.93272929,
       0.58342359, 0.48397811, 0.15581581, 0.71203824, 0.62331612,
       0.24932962, 0.42964752, 0.48854163, 0.21731694, 0.40892649])

In [42]:
pd.cut(data, 4, precision=2)

[(0.024, 0.26], (0.024, 0.26], (0.024, 0.26], (0.74, 0.98], (0.74, 0.98], ..., (0.024, 0.26], (0.26, 0.5], (0.26, 0.5], (0.024, 0.26], (0.26, 0.5]]
Length: 20
Categories (4, interval[float64, right]): [(0.024, 0.26] < (0.26, 0.5] < (0.5, 0.74] < (0.74, 0.98]]

In [43]:
data = np.random.standard_normal(1000)

In [44]:
quartiles = pd.qcut(data, 4, precision=2)

In [45]:
quartiles # obtain roughly equally sized bins.

[(0.68, 3.39], (-0.031, 0.68], (0.68, 3.39], (-0.71, -0.031], (-0.71, -0.031], ..., (-0.031, 0.68], (-0.031, 0.68], (-0.71, -0.031], (-0.031, 0.68], (-2.78, -0.71]]
Length: 1000
Categories (4, interval[float64, right]): [(-2.78, -0.71] < (-0.71, -0.031] < (-0.031, 0.68] < (0.68, 3.39]]

In [46]:
pd.Series(quartiles).value_counts()

(-2.78, -0.71]     250
(-0.71, -0.031]    250
(-0.031, 0.68]     250
(0.68, 3.39]       250
Name: count, dtype: int64

In [47]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-2.7729999999999997, -1.314]    100
(-1.314, -0.0306]                400
(-0.0306, 1.37]                  400
(1.37, 3.388]                    100
Name: count, dtype: int64